/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diseño_segundo;

import diseño_primero.*;

/**
 *
 * @author Cristian Herrera
 */
import formulas_base.ValorCuota_Futuro;
public class Futuro_couta extends javax.swing.JFrame {

    /**
     * Creates new form ConversionT
     */
    
    public Futuro_couta() {
        initComponents();
        setLocationRelativeTo(null);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        P_F = new javax.swing.JLabel();
        P_C_U = new javax.swing.JLabel();
        F_C = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Button_PVencido = new javax.swing.JButton();
        Button_PAnticipado = new javax.swing.JButton();
        Button_VFuturo = new javax.swing.JButton();
        Button_CUniforme = new javax.swing.JButton();
        Button_TPeriodica = new javax.swing.JButton();
        Button_NPeriodos = new javax.swing.JButton();
        Button_IVencido = new javax.swing.JButton();
        Button_IAnticipado = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Caja_CUniforme = new javax.swing.JButton();
        texto_CUniforme = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Caja_VFuturo = new javax.swing.JButton();
        texto_VFuturo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        Caja_TPeriodica = new javax.swing.JButton();
        texto_TPeriodica = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        Caja_NPeriodos = new javax.swing.JButton();
        texto_NPeriodos = new javax.swing.JTextField();
        combo1 = new javax.swing.JComboBox<>();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/linea-gris-0_opt.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 720, 50));

        P_F.setText("Presente / Futuro");
        P_F.setToolTipText("");
        P_F.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P_FMouseClicked(evt);
            }
        });
        getContentPane().add(P_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 125, 40));

        P_C_U.setText("Presente / Couta uniforme");
        P_C_U.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P_C_UMouseClicked(evt);
            }
        });
        getContentPane().add(P_C_U, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, 40));

        F_C.setText("Futuro / Cuota uniforme");
        F_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F_CMouseClicked(evt);
            }
        });
        getContentPane().add(F_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 140, 40));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/casa.jpg"))); // NOI18N
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 8, -1, -1));

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 726, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Button_PVencido.setText("Pago de cuota vencida");
        Button_PVencido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_PVencidoMouseClicked(evt);
            }
        });

        Button_PAnticipado.setText("Pago de cuota anticipada");
        Button_PAnticipado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_PAnticipadoMouseClicked(evt);
            }
        });

        Button_VFuturo.setText("Valor futuro (f)");
        Button_VFuturo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_VFuturoMouseClicked(evt);
            }
        });

        Button_CUniforme.setText("Cuota uniforme (a)");
        Button_CUniforme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_CUniformeMouseClicked(evt);
            }
        });

        Button_TPeriodica.setText("Tasa periodica (i)");
        Button_TPeriodica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_TPeriodicaMouseClicked(evt);
            }
        });

        Button_NPeriodos.setText("No de periodos (n)");
        Button_NPeriodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_NPeriodosMouseClicked(evt);
            }
        });

        Button_IVencido.setText("Interes Vencido");
        Button_IVencido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_IVencidoMouseClicked(evt);
            }
        });

        Button_IAnticipado.setText("Interes Anticipado");
        Button_IAnticipado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_IAnticipadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(Button_PVencido)
                        .addGap(64, 64, 64)
                        .addComponent(Button_PAnticipado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(Button_VFuturo)
                                .addGap(18, 18, 18)
                                .addComponent(Button_CUniforme))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(Button_IVencido)
                                .addGap(46, 46, 46)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Button_TPeriodica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Button_NPeriodos))
                            .addComponent(Button_IAnticipado))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_PVencido)
                    .addComponent(Button_PAnticipado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_IVencido)
                    .addComponent(Button_IAnticipado))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_VFuturo)
                    .addComponent(Button_CUniforme)
                    .addComponent(Button_TPeriodica)
                    .addComponent(Button_NPeriodos))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 710, 140));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Caja_CUniforme.setText("Cuota uniforme (a)");
        Caja_CUniforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Caja_CUniformeActionPerformed(evt);
            }
        });

        texto_CUniforme.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                texto_CUniformeKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Caja_CUniforme, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto_CUniforme)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Caja_CUniforme, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(texto_CUniforme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 140, 120));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Caja_VFuturo.setText("Valor futuro (f)");
        Caja_VFuturo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Caja_VFuturoActionPerformed(evt);
            }
        });

        texto_VFuturo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                texto_VFuturoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Caja_VFuturo, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto_VFuturo)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Caja_VFuturo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(texto_VFuturo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 140, 120));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Caja_TPeriodica.setText("Tasa periodica (i)");

        texto_TPeriodica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                texto_TPeriodicaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Caja_TPeriodica, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(texto_TPeriodica)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Caja_TPeriodica, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(texto_TPeriodica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 140, 120));
        jPanel4.getAccessibleContext().setAccessibleName("");

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Caja_NPeriodos.setText("No de periodos (n)");
        Caja_NPeriodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Caja_NPeriodosActionPerformed(evt);
            }
        });

        texto_NPeriodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_NPeriodosActionPerformed(evt);
            }
        });
        texto_NPeriodos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                texto_NPeriodosKeyTyped(evt);
            }
        });

        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Item", "Dias", "Meses", "Bimestres", "Trimestres", "Semestres", "Años" }));
        combo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo1ItemStateChanged(evt);
            }
        });
        combo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Caja_NPeriodos))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(texto_NPeriodos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Caja_NPeriodos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto_NPeriodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 140, 120));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/fondo2-lanczos3.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        Diseño ds = new Diseño();
        
        ds.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void P_FMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_FMouseClicked
        Presente_futuro pf = new Presente_futuro();
        
        pf.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_P_FMouseClicked

    private void P_C_UMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_C_UMouseClicked
        Presente_cuota pc = new Presente_cuota();
        
        pc.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_P_C_UMouseClicked

    private void F_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F_CMouseClicked
        Futuro_couta fc = new Futuro_couta();
        
        fc.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_F_CMouseClicked

    private void Button_PVencidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_PVencidoMouseClicked
        Button_IVencido.setVisible(true);
        Button_IAnticipado.setVisible(true);
        Button_PAnticipado.setEnabled(false);
    }//GEN-LAST:event_Button_PVencidoMouseClicked

    private void Button_VFuturoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_VFuturoMouseClicked
        jPanel2.setVisible(true);
        Caja_CUniforme.setEnabled(false);
        Caja_TPeriodica.setEnabled(false);
        Caja_NPeriodos.setEnabled(false);
        texto_VFuturo.setEditable(false);
        Button_CUniforme.setEnabled(false);
        Button_TPeriodica.setEnabled(false);
        Button_NPeriodos.setEnabled(false);
    }//GEN-LAST:event_Button_VFuturoMouseClicked

    private void Button_PAnticipadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_PAnticipadoMouseClicked
        Button_IAnticipado.setVisible(true);
        Button_IVencido.setVisible(true);
        Button_PVencido.setEnabled(false);
    }//GEN-LAST:event_Button_PAnticipadoMouseClicked

    private void Button_CUniformeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_CUniformeMouseClicked
        jPanel3.setVisible(true);
        Caja_VFuturo.setEnabled(false);
        Caja_TPeriodica.setEnabled(false);
        Caja_NPeriodos.setEnabled(false);
        texto_CUniforme.setEditable(false);
        Button_VFuturo.setEnabled(false);
        Button_TPeriodica.setEnabled(false);
        Button_NPeriodos.setEnabled(false);
    }//GEN-LAST:event_Button_CUniformeMouseClicked

    private void Button_TPeriodicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_TPeriodicaMouseClicked
        jPanel5.setVisible(true);
        this.texto_NPeriodos.setEnabled(false);
        Caja_CUniforme.setEnabled(false);
        Caja_VFuturo.setEnabled(false);
        Caja_NPeriodos.setEnabled(false);
        texto_TPeriodica.setEditable(false);
        Button_VFuturo.setEnabled(false);
        Button_CUniforme.setEnabled(false);
        Button_NPeriodos.setEnabled(false);
    }//GEN-LAST:event_Button_TPeriodicaMouseClicked

    private void Button_NPeriodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_NPeriodosMouseClicked
        jPanel4.setVisible(true);
        Caja_CUniforme.setEnabled(false);
        Caja_TPeriodica.setEnabled(false);
        Caja_VFuturo.setEnabled(false);
        texto_NPeriodos.setEditable(false);
        Button_VFuturo.setEnabled(false);
        Button_CUniforme.setEnabled(false);
        Button_TPeriodica.setEnabled(false);
    }//GEN-LAST:event_Button_NPeriodosMouseClicked

    private void texto_VFuturoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texto_VFuturoKeyTyped
        if(this.Button_CUniforme.isEnabled()){
            this.jPanel5.setVisible(true);
            this.texto_NPeriodos.setEnabled(false);
        }else if(this.Button_TPeriodica.isEnabled()){
            this.jPanel4.setVisible(true);
        }else if(this.Button_NPeriodos.isEnabled()){
            this.jPanel2.setVisible(true);
        }
    }//GEN-LAST:event_texto_VFuturoKeyTyped

    private void texto_CUniformeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texto_CUniformeKeyTyped
        if(this.Button_VFuturo.isEnabled()){
            this.jPanel5.setVisible(true);
            this.texto_NPeriodos.setEnabled(false);
        }else if(this.Button_TPeriodica.isEnabled()){
            this.jPanel3.setVisible(true);
        }else if(this.Button_NPeriodos.isEnabled()){
            this.jPanel5.setVisible(true);
        }
    }//GEN-LAST:event_texto_CUniformeKeyTyped

    private void texto_TPeriodicaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texto_TPeriodicaKeyTyped
        if(this.Button_VFuturo.isEnabled()){
            this.jPanel3.setVisible(true);
        }else if(this.Button_CUniforme.isEnabled()){
            this.jPanel2.setVisible(true);
        }else if(this.Button_NPeriodos.isEnabled()){
            this.jPanel3.setVisible(true);
        }
    }//GEN-LAST:event_texto_TPeriodicaKeyTyped

    private void texto_NPeriodosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texto_NPeriodosKeyTyped
        
          if(this.Button_VFuturo.isEnabled()){
            this.jPanel4.setVisible(true);
        }else if(this.Button_CUniforme.isEnabled()){
            this.jPanel4.setVisible(true);
        }else if(this.Button_TPeriodica.isEnabled()){
            this.jPanel2.setVisible(true);
        
        }
        
        
    }//GEN-LAST:event_texto_NPeriodosKeyTyped

    private void Caja_VFuturoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Caja_VFuturoActionPerformed
        ValorCuota_Futuro objValor=new ValorCuota_Futuro();
        double cuotaU=Double.parseDouble(this.texto_CUniforme.getText());
        int tasaPVen=Integer.parseInt(this.texto_TPeriodica.getText());
        int periodosN=Integer.parseInt(this.texto_NPeriodos.getText());
        String solucion2;
        
        if(Button_PVencido.isEnabled()){
        if(Button_IVencido.isEnabled()){
        solucion2=objValor.VFuturo_CVencida_IVencido(cuotaU, tasaPVen, periodosN);
        this.texto_VFuturo.setText("$"+solucion2);
        }else if(Button_IAnticipado.isEnabled()){
        solucion2=objValor.VFuturo_CAnticipadaVencida_IAnticipado(cuotaU, tasaPVen, periodosN);
        this.texto_VFuturo.setText(solucion2);
        }
        }else if(Button_PAnticipado.isEnabled()){
        if(Button_IVencido.isEnabled()){
        solucion2=objValor.VFuturo_CAnticipada_IVencido(cuotaU, tasaPVen, periodosN);
        this.texto_VFuturo.setText(solucion2);
        }else if(Button_IAnticipado.isEnabled()){
        solucion2=objValor.VFuturo_CAnticipadaVencida_IAnticipado(cuotaU, tasaPVen, periodosN);
        this.texto_VFuturo.setText(solucion2);
        }
        }
    }//GEN-LAST:event_Caja_VFuturoActionPerformed

    private void Caja_CUniformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Caja_CUniformeActionPerformed
        ValorCuota_Futuro objValor=new ValorCuota_Futuro();
        double valorF=Double.parseDouble(this.texto_VFuturo.getText());
        int tasaPVen=Integer.parseInt(this.texto_TPeriodica.getText());
        int periodosN=Integer.parseInt(this.texto_NPeriodos.getText());
        String solucion2;
        
        if(Button_PVencido.isEnabled()){
        if(Button_IVencido.isEnabled()){
         solucion2=objValor.CUniforme_CVencida_IVencido(valorF, tasaPVen, periodosN);
        this.texto_CUniforme.setText("$"+solucion2);
        }else if(Button_IAnticipado.isEnabled()){
        solucion2=objValor.CUniforme_CVencida_IAnticipado(valorF, tasaPVen, periodosN);
        this.texto_CUniforme.setText("$"+solucion2);
        }
        }else if(Button_PAnticipado.isEnabled()){
        if(Button_IVencido.isEnabled()){
        solucion2=objValor.CUniforme_CAnticipada_IVencido(valorF, tasaPVen, periodosN);
        this.texto_CUniforme.setText("$"+solucion2);
        }else if(Button_IAnticipado.isEnabled()){
        solucion2=objValor.CUniforme_CAnticipada_IAnticipado(valorF, tasaPVen, periodosN);
        this.texto_CUniforme.setText("$"+solucion2);
        }
        }
    }//GEN-LAST:event_Caja_CUniformeActionPerformed

    private void Caja_NPeriodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Caja_NPeriodosActionPerformed
        ValorCuota_Futuro objValor=new ValorCuota_Futuro();
        double valorF=Double.parseDouble(this.texto_VFuturo.getText());
        double cuotaU=Integer.parseInt(this.texto_CUniforme.getText());
        int tasaPVen=Integer.parseInt(this.texto_TPeriodica.getText());
        double solucion;
        
        if(Button_PVencido.isEnabled()){
        if(Button_IVencido.isEnabled()){
         solucion=objValor.NPeriodos_CVencida_IVencido(valorF, cuotaU, tasaPVen);
        this.texto_NPeriodos.setText(Double.toString(solucion));
        }else if(Button_IAnticipado.isEnabled()){
        solucion=objValor.NPeriodos_CVencida_IAnticipado(valorF, cuotaU, tasaPVen);
        this.texto_NPeriodos.setText(Double.toString(solucion));
        }
        }else if(Button_PAnticipado.isEnabled()){
        if(Button_IVencido.isEnabled()){
        solucion=objValor.NPeriodos_CAnticipada_IVencido(valorF, cuotaU, tasaPVen);
        this.texto_NPeriodos.setText(Double.toString(solucion));
        }else if(Button_IAnticipado.isEnabled()){
        solucion=objValor.NPeriodos_CAnticipada_IAnticipado(valorF, cuotaU, tasaPVen);
        this.texto_NPeriodos.setText(Double.toString(solucion));
        }
        }
    }//GEN-LAST:event_Caja_NPeriodosActionPerformed

    private void combo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo1MouseClicked
        
        
        
    }//GEN-LAST:event_combo1MouseClicked

    private void combo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo1ItemStateChanged
        if(this.combo1.getSelectedItem().toString().equals("Select Item")){
        this.texto_NPeriodos.setEnabled(false);
        }else{
        this.texto_NPeriodos.setEnabled(true);
        }
    }//GEN-LAST:event_combo1ItemStateChanged

    private void Button_IVencidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_IVencidoMouseClicked
        Button_IAnticipado.setEnabled(false);
        Caja_VFuturo.setVisible(true);
        Caja_CUniforme.setVisible(true);
        Caja_TPeriodica.setVisible(true);
        Caja_NPeriodos.setVisible(true);
    }//GEN-LAST:event_Button_IVencidoMouseClicked

    private void Button_IAnticipadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_IAnticipadoMouseClicked
        Button_IVencido.setEnabled(false);
        Caja_VFuturo.setVisible(true);
        Caja_CUniforme.setVisible(true);
        Caja_TPeriodica.setVisible(true);
        Caja_NPeriodos.setVisible(true);
    }//GEN-LAST:event_Button_IAnticipadoMouseClicked

    private void texto_NPeriodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_NPeriodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_NPeriodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Futuro_couta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Futuro_couta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Futuro_couta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Futuro_couta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Futuro_couta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_CUniforme;
    private javax.swing.JButton Button_IAnticipado;
    private javax.swing.JButton Button_IVencido;
    private javax.swing.JButton Button_NPeriodos;
    private javax.swing.JButton Button_PAnticipado;
    private javax.swing.JButton Button_PVencido;
    private javax.swing.JButton Button_TPeriodica;
    private javax.swing.JButton Button_VFuturo;
    private javax.swing.JButton Caja_CUniforme;
    private javax.swing.JButton Caja_NPeriodos;
    private javax.swing.JButton Caja_TPeriodica;
    private javax.swing.JButton Caja_VFuturo;
    private javax.swing.JLabel F_C;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Home;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel P_C_U;
    private javax.swing.JLabel P_F;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField texto_CUniforme;
    private javax.swing.JTextField texto_NPeriodos;
    private javax.swing.JTextField texto_TPeriodica;
    private javax.swing.JTextField texto_VFuturo;
    // End of variables declaration//GEN-END:variables
}
