/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diseño_segundo;

import Modelo.segungo.Presente_cuota_modelo;
import diseño_primero.*;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian Herrera
 */
public class Presente_cuota extends javax.swing.JFrame {

    DecimalFormat formato = new DecimalFormat("#.##");
    
    public Presente_cuota() {
        initComponents();
        setLocationRelativeTo(null);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        
        valorPresente.setVisible(false);
        cuotaUniforme.setVisible(false);
        tasaPeriodica.setVisible(false);
        numeroPeriodos.setVisible(false);
        
        interesAnticipado.setVisible(false);
        interesVencido.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        P_F = new javax.swing.JLabel();
        P_C_U = new javax.swing.JLabel();
        F_C = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pagoVencido = new javax.swing.JButton();
        pagoAnticipado = new javax.swing.JButton();
        valorPresente = new javax.swing.JButton();
        cuotaUniforme = new javax.swing.JButton();
        tasaPeriodica = new javax.swing.JButton();
        numeroPeriodos = new javax.swing.JButton();
        interesVencido = new javax.swing.JButton();
        interesAnticipado = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        a = new javax.swing.JButton();
        txtA = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        p = new javax.swing.JButton();
        txtP = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        i = new javax.swing.JButton();
        txtI = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        n = new javax.swing.JButton();
        txtN = new javax.swing.JTextField();
        cmbDato = new javax.swing.JComboBox<>();
        btnVolverElegir = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/linea-gris-0_opt.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 720, 50));

        P_F.setText("Presente / Futuro");
        P_F.setToolTipText("");
        P_F.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P_FMouseClicked(evt);
            }
        });
        getContentPane().add(P_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 125, 40));

        P_C_U.setText("Presente / Couta uniforme");
        P_C_U.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P_C_UMouseClicked(evt);
            }
        });
        getContentPane().add(P_C_U, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, 40));

        F_C.setText("Futuro / Cuota uniforme");
        F_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F_CMouseClicked(evt);
            }
        });
        getContentPane().add(F_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 140, 40));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/casa.jpg"))); // NOI18N
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 8, -1, -1));

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 726, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pagoVencido.setText("Pago de cuota vencida");
        pagoVencido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagoVencidoActionPerformed(evt);
            }
        });

        pagoAnticipado.setText("Pago de cuota anticipada");
        pagoAnticipado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagoAnticipadoActionPerformed(evt);
            }
        });

        valorPresente.setText("Valor presente (p)");
        valorPresente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorPresenteActionPerformed(evt);
            }
        });

        cuotaUniforme.setText("Cuota uniforme (a)");
        cuotaUniforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuotaUniformeActionPerformed(evt);
            }
        });

        tasaPeriodica.setText("Tasa periodica (i)");
        tasaPeriodica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasaPeriodicaActionPerformed(evt);
            }
        });

        numeroPeriodos.setText("No de periodos (n)");
        numeroPeriodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroPeriodosActionPerformed(evt);
            }
        });

        interesVencido.setText("Interes Vencido");
        interesVencido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interesVencidoActionPerformed(evt);
            }
        });

        interesAnticipado.setText("Interes Anticipado");
        interesAnticipado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interesAnticipadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pagoVencido)
                            .addComponent(interesVencido))
                        .addGap(62, 62, 62))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(valorPresente)
                        .addGap(18, 18, 18)
                        .addComponent(cuotaUniforme)
                        .addGap(61, 61, 61)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tasaPeriodica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numeroPeriodos)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pagoAnticipado)
                            .addComponent(interesAnticipado))
                        .addGap(164, 164, 164))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pagoVencido)
                    .addComponent(pagoAnticipado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(interesAnticipado)
                    .addComponent(interesVencido))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valorPresente)
                    .addComponent(cuotaUniforme)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tasaPeriodica)
                        .addComponent(numeroPeriodos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 710, 140));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        a.setText("Cuota uniforme (a)");
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });

        txtA.setText("0");
        txtA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAActionPerformed(evt);
            }
        });
        txtA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(a, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtA)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 140, 120));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        p.setText("Valor presente (p)");
        p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pActionPerformed(evt);
            }
        });

        txtP.setText("0");
        txtP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPActionPerformed(evt);
            }
        });
        txtP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtP)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 140, 120));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        i.setText("Tasa periodica (i)");
        i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iActionPerformed(evt);
            }
        });

        txtI.setText("0");
        txtI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIKeyTyped(evt);
            }
        });

        jLabel1.setText("%");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(i, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(i, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 140, 120));
        jPanel4.getAccessibleContext().setAccessibleName("");

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        n.setText("No de periodos (n)");
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });

        txtN.setText("0");
        txtN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNKeyTyped(evt);
            }
        });

        cmbDato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dias", "Meses", "Bimestres", "Trimestres", "Semestres", "Años" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(n, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDato, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 140, 120));

        btnVolverElegir.setText("Volver a Elegir");
        btnVolverElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverElegirActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolverElegir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/fondo2-lanczos3.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        Diseño ds = new Diseño();
        
        ds.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void P_FMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_FMouseClicked
        Presente_futuro pf = new Presente_futuro();        
        pf.setVisible(true);       
        this.dispose();
    }//GEN-LAST:event_P_FMouseClicked

    private void P_C_UMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_C_UMouseClicked
        Presente_cuota pc = new Presente_cuota();       
        pc.setVisible(true);      
        this.dispose();
    }//GEN-LAST:event_P_C_UMouseClicked

    private void valorPresenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorPresenteActionPerformed
        jPanel2.setVisible(true);
        cuotaUniforme.setEnabled(false);
        tasaPeriodica.setEnabled(false);
        numeroPeriodos.setEnabled(false);
        
        p.setEnabled(true);
        a.setEnabled(false);
        i.setEnabled(false);
        n.setEnabled(false);
        
        txtP.setEditable(false);
    }//GEN-LAST:event_valorPresenteActionPerformed

    private void cuotaUniformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuotaUniformeActionPerformed
        jPanel3.setVisible(true);
        valorPresente.setEnabled(false);
        tasaPeriodica.setEnabled(false);
        numeroPeriodos.setEnabled(false);
        
        p.setEnabled(false);
        a.setEnabled(true);
        i.setEnabled(false);
        n.setEnabled(false);
        
        txtA.setEditable(false);
    }//GEN-LAST:event_cuotaUniformeActionPerformed

    private void tasaPeriodicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasaPeriodicaActionPerformed
        jPanel5.setVisible(true);
    }//GEN-LAST:event_tasaPeriodicaActionPerformed

    private void numeroPeriodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroPeriodosActionPerformed
        jPanel4.setVisible(true);

        cuotaUniforme.setEnabled(false);
        tasaPeriodica.setEnabled(false);
        valorPresente.setEnabled(false);
        
        p.setEnabled(false);
        a.setEnabled(false);
        i.setEnabled(false);
        n.setEnabled(true);
        
        txtN.setEditable(false);
    }//GEN-LAST:event_numeroPeriodosActionPerformed

    private void txtAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAKeyTyped

        char numero = evt.getKeyChar();
        if((numero<'0' || numero>'9') && (numero<',' || numero>'.')){
            evt.consume();
        }
        
        jPanel5.setVisible(true);

        if (tasaPeriodica.isEnabled()) {
            jPanel3.setVisible(true);
        }
        if (numeroPeriodos.isEnabled()) {
            jPanel5.setVisible(true);
        }
    }//GEN-LAST:event_txtAKeyTyped

    private void txtNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNKeyTyped
        jPanel4.setVisible(true);
        char numero = evt.getKeyChar();
        if((numero<'0' || numero>'9') && (numero<',' || numero>'.')){
            evt.consume();
        }
        
        if (valorPresente.isEnabled()) {
            jPanel4.setVisible(true);
        }

        if (cuotaUniforme.isEnabled()) {
            jPanel4.setVisible(true);
        }

        if (tasaPeriodica.isEnabled()) {
            jPanel2.setVisible(true);
        }
    }//GEN-LAST:event_txtNKeyTyped

    private void txtIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIKeyTyped

        char numero = evt.getKeyChar();
        if((numero<'0' || numero>'9') && (numero<',' || numero>'.')){
            evt.consume();
        }
        
        jPanel3.setVisible(true);

        if (numeroPeriodos.isEnabled()) {
            jPanel3.setVisible(true);
        }

        if (cuotaUniforme.isEnabled()) {
            jPanel2.setVisible(true);
        }
        
    }//GEN-LAST:event_txtIKeyTyped

    private void F_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F_CMouseClicked
        Futuro_couta fc = new Futuro_couta();
        fc.setVisible(true);      
        this.dispose();
    }//GEN-LAST:event_F_CMouseClicked

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        double a = Double.parseDouble(txtA.getText());
        double p = Double.parseDouble(txtP.getText());
        double i = Double.parseDouble(txtI.getText());
        double n = Double.parseDouble(txtN.getText());
        double total = 0;
        
        Presente_cuota_modelo obj = new Presente_cuota_modelo(a, p, i, n);
        
        if (pagoVencido.isEnabled() && interesVencido.isEnabled() && cuotaUniforme.isEnabled()) {
            total = obj.cuota_uniforme_vencida_pagoVencida();
            
        }else if(pagoAnticipado.isEnabled() && interesVencido.isEnabled() && cuotaUniforme.isEnabled()) {
            total = obj.cuota_uniforme_vencida_pagoAnticipado();
        }
        
        txtA.setText(""+formato.format(total));
        
    }//GEN-LAST:event_aActionPerformed

    private void pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pActionPerformed
        double a = Double.parseDouble(txtA.getText());
        double p = Double.parseDouble(txtP.getText());
        double i = Double.parseDouble(txtI.getText());
        double n = Double.parseDouble(txtN.getText());
        double total = 0;
        
        Presente_cuota_modelo obj = new Presente_cuota_modelo(a, p, i, n);
        
        if (pagoVencido.isEnabled() && interesVencido.isEnabled() && valorPresente.isEnabled()) {
            total = obj.valor_presente_vencida_pagoVencida();
            
        }else if(pagoAnticipado.isEnabled() && interesVencido.isEnabled() && valorPresente.isEnabled()) {
            total = obj.valor_presente_vencida_pagoAnticipado();
        }
        
        txtP.setText(""+formato.format(total));
    }//GEN-LAST:event_pActionPerformed

    private void txtPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPKeyTyped
        char numero = evt.getKeyChar();
        if((numero<'0' || numero>'9') && (numero<',' || numero>'.')){
            evt.consume();
        }
        
        if (tasaPeriodica.isEnabled()) {
            jPanel4.setVisible(true);
        }
        if (numeroPeriodos.isEnabled()) {
            jPanel2.setVisible(true);
        }
        if (cuotaUniforme.isEnabled()) {
            jPanel5.setVisible(true);
        }
    }//GEN-LAST:event_txtPKeyTyped

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        double a = Double.parseDouble(txtA.getText());
        double p = Double.parseDouble(txtP.getText());
        double i = Double.parseDouble(txtI.getText());
        double n = Double.parseDouble(txtN.getText());
        double total = 0;
        
        Presente_cuota_modelo obj = new Presente_cuota_modelo(a, p, i, n);
        
        if (pagoVencido.isEnabled() && interesVencido.isEnabled() && numeroPeriodos.isEnabled()) {
            total = obj.n_periodos_vencida_pagoVencida();
            
        }else if(pagoAnticipado.isEnabled() && interesVencido.isEnabled() && numeroPeriodos.isEnabled()) {
            total = obj.n_periodos_vencida_pagoAnticipado();
        }
        
        txtN.setText(""+formato.format(total));
    }//GEN-LAST:event_nActionPerformed

    private void btnVolverElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverElegirActionPerformed
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);

        valorPresente.setVisible(false);
        cuotaUniforme.setVisible(false);
        tasaPeriodica.setVisible(false);
        numeroPeriodos.setVisible(false);
        
        interesAnticipado.setVisible(false);
        interesVencido.setVisible(false);
        
        pagoVencido.setEnabled(true);
        pagoAnticipado.setEnabled(true);
        interesAnticipado.setEnabled(true);
        interesVencido.setEnabled(true);
        valorPresente.setEnabled(true);
        cuotaUniforme.setEnabled(true);
        tasaPeriodica.setEnabled(true);
        numeroPeriodos.setEnabled(true);
        p.setEnabled(true);
        a.setEnabled(true);
        i.setEnabled(true);
        n.setEnabled(true);
        
        txtN.setEditable(true);
        txtA.setEditable(true);
        txtI.setEditable(true);
        txtP.setEditable(true);
        
        txtN.setText("0");
        txtA.setText("0");
        txtI.setText("0");
        txtP.setText("0");
    }//GEN-LAST:event_btnVolverElegirActionPerformed

    private void pagoVencidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagoVencidoActionPerformed
        pagoAnticipado.setEnabled(false);
        
        interesAnticipado.setVisible(true);
        interesVencido.setVisible(true);
    }//GEN-LAST:event_pagoVencidoActionPerformed

    private void pagoAnticipadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagoAnticipadoActionPerformed
        pagoVencido.setEnabled(false);
        
        interesAnticipado.setVisible(true);
        interesVencido.setVisible(true);
        
    }//GEN-LAST:event_pagoAnticipadoActionPerformed

    private void txtPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPActionPerformed

    private void txtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAActionPerformed

    private void interesVencidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interesVencidoActionPerformed
        interesAnticipado.setEnabled(false);
        
        valorPresente.setVisible(true);
        cuotaUniforme.setVisible(true);
        tasaPeriodica.setVisible(true);
        numeroPeriodos.setVisible(true);
    }//GEN-LAST:event_interesVencidoActionPerformed

    private void interesAnticipadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interesAnticipadoActionPerformed
        interesVencido.setEnabled(false);
        
        valorPresente.setVisible(true);
        cuotaUniforme.setVisible(true);
        tasaPeriodica.setVisible(true);
        numeroPeriodos.setVisible(true);
    }//GEN-LAST:event_interesAnticipadoActionPerformed

    private void iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iActionPerformed
        
    }//GEN-LAST:event_iActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Presente_cuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Presente_cuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Presente_cuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Presente_cuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Presente_cuota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel F_C;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Home;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel P_C_U;
    private javax.swing.JLabel P_F;
    private javax.swing.JButton a;
    private javax.swing.JButton btnVolverElegir;
    private javax.swing.JComboBox<String> cmbDato;
    private javax.swing.JButton cuotaUniforme;
    private javax.swing.JButton i;
    private javax.swing.JButton interesAnticipado;
    private javax.swing.JButton interesVencido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton n;
    private javax.swing.JButton numeroPeriodos;
    private javax.swing.JButton p;
    private javax.swing.JButton pagoAnticipado;
    private javax.swing.JButton pagoVencido;
    private javax.swing.JButton tasaPeriodica;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtI;
    private javax.swing.JTextField txtN;
    private javax.swing.JTextField txtP;
    private javax.swing.JButton valorPresente;
    // End of variables declaration//GEN-END:variables
}
