/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diseño_segundo;

import diseño_primero.*;

/**
 *
 * @author Cristian Herrera
 */
public class Valor_del_dinero extends javax.swing.JFrame {

    /**
     * Creates new form ConversionT
     */
    public Valor_del_dinero() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo1 = new javax.swing.JLabel();
        Logo2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Cuadro2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Cuadro1 = new javax.swing.JLabel();
        Logo3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Cuadro3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        P_F = new javax.swing.JLabel();
        P_C_U = new javax.swing.JLabel();
        F_C = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/descuento.jpg"))); // NOI18N
        getContentPane().add(Logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 50, 50));

        Logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/moneda.jpg"))); // NOI18N
        getContentPane().add(Logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        jLabel2.setText("Valor del dinero");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        Cuadro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/color blanco.jpg"))); // NOI18N
        Cuadro2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Cuadro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 110, 110));

        jLabel1.setText("<html>Conversión de <br> <center>tasas</center></html>");
        jLabel1.setName(""); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 320, 80, -1));

        Cuadro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/color blanco.jpg"))); // NOI18N
        Cuadro1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Cuadro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cuadro1MouseClicked(evt);
            }
        });
        getContentPane().add(Cuadro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 110, 110));

        Logo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/tarjeta-de-debito.jpg"))); // NOI18N
        getContentPane().add(Logo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        jLabel3.setText("<html>Simulador de <br><center>credito</center><html>");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 320, -1, -1));

        Cuadro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/color blanco.jpg"))); // NOI18N
        Cuadro3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Cuadro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 110, 110));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/linea-gris-0_opt.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 650, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/uts_opt.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel5.setText("Valor del dinero");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 450, 100));

        P_F.setText("Presente / Futuro");
        P_F.setToolTipText("");
        P_F.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P_FMouseClicked(evt);
            }
        });
        getContentPane().add(P_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 0, 125, 40));

        P_C_U.setText("Presente / Couta uniforme");
        P_C_U.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P_C_UMouseClicked(evt);
            }
        });
        getContentPane().add(P_C_U, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 0, -1, 40));

        F_C.setText("Futuro / Cuota uniforme");
        F_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F_CMouseClicked(evt);
            }
        });
        getContentPane().add(F_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 0, 140, 40));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/casa.jpg"))); // NOI18N
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 8, -1, -1));

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/fondo1.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cuadro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cuadro1MouseClicked
        Valor_del_dinero ct = new Valor_del_dinero();
        ct.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_Cuadro1MouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        Diseño ds = new Diseño();
        
        ds.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void P_FMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_FMouseClicked
        Presente_futuro pf = new Presente_futuro();
        
        pf.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_P_FMouseClicked

    private void P_C_UMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_C_UMouseClicked
        Presente_cuota pc = new Presente_cuota();
        
        pc.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_P_C_UMouseClicked

    private void F_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F_CMouseClicked
        Futuro_couta fc = new Futuro_couta();
        
        fc.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_F_CMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Valor_del_dinero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Valor_del_dinero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Valor_del_dinero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Valor_del_dinero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Valor_del_dinero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cuadro1;
    private javax.swing.JLabel Cuadro2;
    private javax.swing.JLabel Cuadro3;
    private javax.swing.JLabel F_C;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel Logo2;
    private javax.swing.JLabel Logo3;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel P_C_U;
    private javax.swing.JLabel P_F;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
