/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diseño_primero;

/**
 *
 * @author Cristian Herrera
 */
public class ConversionT extends javax.swing.JFrame {

    /**
     * Creates new form ConversionT
     */
    public ConversionT() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        N_P_E = new javax.swing.JLabel();
        Tasas_e = new javax.swing.JLabel();
        Periodica = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/linea-gris-0_opt.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 620, 50));

        N_P_E.setText("Nominal / Periodica / Efectiva");
        N_P_E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                N_P_EMouseClicked(evt);
            }
        });
        getContentPane().add(N_P_E, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 0, 170, 40));

        Tasas_e.setText("Tasas Equivalente");
        Tasas_e.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tasas_eMouseClicked(evt);
            }
        });
        getContentPane().add(Tasas_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 0, -1, 40));

        Periodica.setText("Periodica");
        getContentPane().add(Periodica, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 80, 40));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/casa.jpg"))); // NOI18N
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 8, -1, -1));

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/50.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/20.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/oie_transparent (2).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jScrollPane1.setAutoscrolls(true);

        jTextPane1.setEditable(false);
        jTextPane1.setText("Las fórmulas de convertibilidad de tasas son herramientas que nos ayudan a  convertir una tasa nominal a una tasa  efectiva o viceversa, convertir una tasa efectiva a una nominal. Esto es de gran ayuda ya que en ocasiones queremos comparar las tasas que nos ofrecen ciertos servicios y para esto debemos convertirlas a tasas anuales o en su defecto a aquella que más nos favorezca.");
        jTextPane1.setAutoscrolls(false);
        jTextPane1.setCaretPosition(1);
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 220, 170));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/fondo1.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        Diseño ds = new Diseño();
        
        ds.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void N_P_EMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_P_EMouseClicked
        Npe n = new Npe();
        
        n.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_N_P_EMouseClicked

    private void Tasas_eMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tasas_eMouseClicked
        TasasE te = new TasasE();
        
        te.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_Tasas_eMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversionT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversionT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversionT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversionT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversionT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Home;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel N_P_E;
    private javax.swing.JLabel Periodica;
    private javax.swing.JLabel Tasas_e;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
