/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diseño_primero;

import Modelo.primero.Npe_modelo;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

public class Npe extends javax.swing.JFrame {

    DecimalFormat formato = new DecimalFormat("#.######");
    
    public Npe() {
        initComponents();
        setLocationRelativeTo(null);
        
        bgRadio.add(radioAnticipada);
        bgRadio.add(radioVencida);
        
        txtefectiva.setText("0");
        txtnominal.setText("0");
        txtperiodica.setText("0");
        
        btnEfectiva.setEnabled(false);
        btnNominal.setEnabled(false);
        btnPeriodica.setEnabled(false);
        
        jPanel4.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgRadio = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        N_P_E = new javax.swing.JLabel();
        Tasas_e = new javax.swing.JLabel();
        Periodica = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelNomina = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtnominal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnNominal = new javax.swing.JButton();
        panelPeriodica = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtperiodica = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnPeriodica = new javax.swing.JButton();
        panelEfectiva = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtefectiva = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnEfectiva = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        radioAnticipada = new javax.swing.JRadioButton();
        radioVencida = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        cmbperiodo = new javax.swing.JComboBox<>();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/linea-gris-0_opt.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 10, 645, 50));

        N_P_E.setText("Nominal / Periodica / Efectiva");
        N_P_E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                N_P_EMouseClicked(evt);
            }
        });
        getContentPane().add(N_P_E, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 0, 170, 40));

        Tasas_e.setText("Tasas Equivalente");
        Tasas_e.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tasas_eMouseClicked(evt);
            }
        });
        getContentPane().add(Tasas_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 0, -1, 40));

        Periodica.setText("Periodica");
        Periodica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PeriodicaMouseClicked(evt);
            }
        });
        getContentPane().add(Periodica, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 80, 40));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/casa.jpg"))); // NOI18N
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 8, -1, -1));

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/Captura.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        panelNomina.setBackground(new java.awt.Color(255, 255, 255));
        panelNomina.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Tasa de Interés Nominal");

        txtnominal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnominalKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnominalKeyTyped(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N

        btnNominal.setText("Convertir");
        btnNominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNominalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNominaLayout = new javax.swing.GroupLayout(panelNomina);
        panelNomina.setLayout(panelNominaLayout);
        panelNominaLayout.setHorizontalGroup(
            panelNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNominaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNominaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelNominaLayout.createSequentialGroup()
                        .addComponent(txtnominal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNominaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNominal)
                .addGap(31, 31, 31))
        );
        panelNominaLayout.setVerticalGroup(
            panelNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNominaLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNominaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtnominal)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNominal)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        getContentPane().add(panelNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 150, 110));

        panelPeriodica.setBackground(new java.awt.Color(255, 255, 255));
        panelPeriodica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Tasa de Interés Periodica");

        txtperiodica.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtperiodicaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtperiodicaKeyTyped(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N

        btnPeriodica.setText("Convertir");
        btnPeriodica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeriodicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPeriodicaLayout = new javax.swing.GroupLayout(panelPeriodica);
        panelPeriodica.setLayout(panelPeriodicaLayout);
        panelPeriodicaLayout.setHorizontalGroup(
            panelPeriodicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
            .addGroup(panelPeriodicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtperiodica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(panelPeriodicaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnPeriodica)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPeriodicaLayout.setVerticalGroup(
            panelPeriodicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPeriodicaLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPeriodicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtperiodica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPeriodica)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        getContentPane().add(panelPeriodica, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 150, 110));

        panelEfectiva.setBackground(new java.awt.Color(255, 255, 255));
        panelEfectiva.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Tasa de Interés Efectiva");

        txtefectiva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtefectivaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtefectivaKeyTyped(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N

        btnEfectiva.setText("Convertir");
        btnEfectiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfectivaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEfectivaLayout = new javax.swing.GroupLayout(panelEfectiva);
        panelEfectiva.setLayout(panelEfectivaLayout);
        panelEfectivaLayout.setHorizontalGroup(
            panelEfectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEfectivaLayout.createSequentialGroup()
                .addGroup(panelEfectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEfectivaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelEfectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(panelEfectivaLayout.createSequentialGroup()
                                .addComponent(txtefectiva, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelEfectivaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnEfectiva)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEfectivaLayout.setVerticalGroup(
            panelEfectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEfectivaLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEfectivaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtefectiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEfectiva)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        getContentPane().add(panelEfectiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 150, 110));

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Forma de pago");
        jLabel9.setToolTipText("");

        radioAnticipada.setText("Anticipada");

        radioVencida.setText("Vencida");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Periodo de pago");
        jLabel10.setToolTipText("");

        cmbperiodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Mes", "Bimestre", "Trimestre", "Semestre", "Año" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(radioAnticipada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(radioVencida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(cmbperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioAnticipada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioVencida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 150, 150));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/fondo1.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        Diseño ds = new Diseño();
        ds.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void txtnominalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnominalKeyTyped
        jPanel4.setVisible(true);
        char numero = evt.getKeyChar();
        if((numero<'0' || numero>'9') && (numero<',' || numero>'.')){
            evt.consume();
        }
    }//GEN-LAST:event_txtnominalKeyTyped

    private void txtefectivaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtefectivaKeyTyped
        jPanel4.setVisible(true);
        char numero = evt.getKeyChar();
        if((numero<'0' || numero>'9') && (numero<',' || numero>'.')){
            evt.consume();
        }

    }//GEN-LAST:event_txtefectivaKeyTyped

    private void txtperiodicaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtperiodicaKeyTyped
        jPanel4.setVisible(true);
        char numero = evt.getKeyChar();
        if((numero<'0' || numero>'9') && (numero<',' || numero>'.')){
            evt.consume();
        }
    }//GEN-LAST:event_txtperiodicaKeyTyped

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        txtefectiva.setText("0");
        txtnominal.setText("0");
        txtperiodica.setText("0");
        
        btnEfectiva.setEnabled(false);
        btnNominal.setEnabled(false);
        btnPeriodica.setEnabled(false);
        
        btnEfectiva.setVisible(true);
        btnNominal.setVisible(true);
        btnPeriodica.setVisible(true);
        
        txtefectiva.setEnabled(true);
        txtnominal.setEnabled(true);
        txtperiodica.setEnabled(true);
        
        jPanel4.setVisible(false);
        
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void N_P_EMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_P_EMouseClicked
        Npe n = new Npe();     
        n.setVisible(true);      
        this.dispose();
    }//GEN-LAST:event_N_P_EMouseClicked

    private void Tasas_eMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tasas_eMouseClicked
        TasasE te = new TasasE();       
        te.setVisible(true);       
        this.dispose();
    }//GEN-LAST:event_Tasas_eMouseClicked

    private void PeriodicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PeriodicaMouseClicked
        Periodica p = new Periodica();      
        p.setVisible(true);       
        this.dispose();
    }//GEN-LAST:event_PeriodicaMouseClicked

    private void btnEfectivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfectivaActionPerformed
        double nominal = Double.parseDouble(txtnominal.getText());
        double periodica = Double.parseDouble(txtperiodica.getText());
        double efectiva = Double.parseDouble(txtefectiva.getText());
        int periodo = cmbperiodo.getSelectedIndex();
        String formaPago = "";
        
        Npe_modelo npe = new Npe_modelo(nominal, periodica, efectiva, periodo, formaPago);
        
        if (radioAnticipada.isSelected()) {
            double efeVenNominal = npe.efectiva_anticipada_nominal();
            txtperiodica.setText(""+formato.format(efeVenNominal));
            double efeVenPeriodica = npe.efectiva_anticipada_vencida_nominal(efeVenNominal);
            txtnominal.setText(""+formato.format(efeVenPeriodica));
        }
        
        if (radioVencida.isSelected()) {  
            double efeVenNominal = npe.efectiva_vencida_nominal();
            txtperiodica.setText(""+formato.format(efeVenNominal));
            double efeVenPeriodica = npe.efectiva_anticipada_vencida_nominal(efeVenNominal);
            txtnominal.setText(""+formato.format(efeVenPeriodica));
        }
        
        btnEfectiva.setEnabled(false);
        btnNominal.setVisible(true);
        btnPeriodica.setVisible(true);
        txtnominal.setEnabled(true);
        txtperiodica.setEnabled(true);
 
    }//GEN-LAST:event_btnEfectivaActionPerformed

    private void txtnominalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnominalKeyPressed
        btnNominal.setEnabled(true);
        btnEfectiva.setVisible(false);
        btnPeriodica.setVisible(false);
        txtefectiva.setEnabled(false);
        txtperiodica.setEnabled(false);
        
    }//GEN-LAST:event_txtnominalKeyPressed

    private void btnNominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNominalActionPerformed
        
        double nominal = Double.parseDouble(txtnominal.getText());
        double periodica = Double.parseDouble(txtperiodica.getText());
        double efectiva = Double.parseDouble(txtefectiva.getText());
        int periodo = cmbperiodo.getSelectedIndex();
        String formaPago = "";

        Npe_modelo npe = new Npe_modelo(nominal, periodica, efectiva, periodo, formaPago);
        
        if (radioAnticipada.isSelected()) {
            double nomAntPeriodica = npe.nominal_anticipada_vencida_periodica();
            txtperiodica.setText(""+formato.format(nomAntPeriodica));
            double nomAntEfectiva = npe.nominal_anticipada_efectiva(nomAntPeriodica);
            txtefectiva.setText(""+formato.format(nomAntEfectiva));
            
        }
        
        if (radioVencida.isSelected()) {           
            double nomVenPeriodica = npe.nominal_anticipada_vencida_periodica();
            txtperiodica.setText(""+formato.format(nomVenPeriodica));
            double nomVenEfectiva = npe.nominal_vencida_efectiva(nomVenPeriodica);
            txtefectiva.setText(""+formato.format(nomVenEfectiva));
            
        }
        
        btnNominal.setEnabled(false);
        btnEfectiva.setVisible(true);
        btnPeriodica.setVisible(true);
        txtefectiva.setEnabled(true);
        txtperiodica.setEnabled(true);
    }//GEN-LAST:event_btnNominalActionPerformed

    private void btnPeriodicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeriodicaActionPerformed
        double nominal = Double.parseDouble(txtnominal.getText());
        double periodica = Double.parseDouble(txtperiodica.getText());
        double efectiva = Double.parseDouble(txtefectiva.getText());
        int periodo = cmbperiodo.getSelectedIndex();
        String formaPago = "";

        Npe_modelo npe = new Npe_modelo(nominal, periodica, efectiva, periodo, formaPago);
        
        if (radioAnticipada.isSelected()) {
            double nomAntPeriodica = npe.periodica_anticipada_efectiva();
            txtefectiva.setText(""+formato.format(nomAntPeriodica));
            double nomAntEfectiva = npe.periodica_anticipada_vencida_nominal();
            txtnominal.setText(""+formato.format(nomAntEfectiva));
            
        }
        
        if (radioVencida.isSelected()) {           
            double nomVenPeriodica = npe.periodica_vencida_efectiva();
            txtefectiva.setText(""+formato.format(nomVenPeriodica));
            double nomAntEfectiva = npe.periodica_anticipada_vencida_nominal();
            txtnominal.setText(""+formato.format(nomAntEfectiva));   
        }
        
        btnPeriodica.setEnabled(false);
        btnNominal.setVisible(true);
        btnEfectiva.setVisible(true);
        txtefectiva.setEnabled(true);
        txtnominal.setEnabled(true);
        
    }//GEN-LAST:event_btnPeriodicaActionPerformed

    private void txtperiodicaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtperiodicaKeyPressed
        btnPeriodica.setEnabled(true);
        btnNominal.setVisible(false);
        btnEfectiva.setVisible(false);
        txtefectiva.setEnabled(false);
        txtnominal.setEnabled(false);
        
    }//GEN-LAST:event_txtperiodicaKeyPressed

    private void txtefectivaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtefectivaKeyPressed
        btnEfectiva.setEnabled(true);
        btnNominal.setVisible(false);
        btnPeriodica.setVisible(false);
        txtnominal.setEnabled(false);
        txtperiodica.setEnabled(false);
    }//GEN-LAST:event_txtefectivaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Npe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Npe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Npe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Npe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Npe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Home;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel N_P_E;
    private javax.swing.JLabel Periodica;
    private javax.swing.JLabel Tasas_e;
    private javax.swing.ButtonGroup bgRadio;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnEfectiva;
    private javax.swing.JButton btnNominal;
    private javax.swing.JButton btnPeriodica;
    private javax.swing.JComboBox<String> cmbperiodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel panelEfectiva;
    private javax.swing.JPanel panelNomina;
    private javax.swing.JPanel panelPeriodica;
    private javax.swing.JRadioButton radioAnticipada;
    private javax.swing.JRadioButton radioVencida;
    private javax.swing.JTextField txtefectiva;
    private javax.swing.JTextField txtnominal;
    private javax.swing.JTextField txtperiodica;
    // End of variables declaration//GEN-END:variables
}
