/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diseño_primero;

/**
 *
 * @author Cristian Herrera
 */
import formulas_base.Interes_periodico;
import javax.swing.JOptionPane;
public class Periodica extends javax.swing.JFrame {

    /**
     * Creates new form ConversionT
     */
    public Periodica() {
        initComponents();
        setLocationRelativeTo(null);
        txtPrueba.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        N_P_E = new javax.swing.JLabel();
        Tasas_e = new javax.swing.JLabel();
        Periodica = new javax.swing.JLabel();
        Home = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtEfectivo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rbtnAnticipado = new javax.swing.JRadioButton();
        rbtnVencido = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        cboxPeriodos = new javax.swing.JComboBox<>();
        txtPrueba = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        rbtnAnticipado2 = new javax.swing.JRadioButton();
        rbtnVencido2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        cboxPeriodos2 = new javax.swing.JComboBox<>();
        txtSalida = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        N_P_E.setText("Nominal / Periodica / Efectiva");
        N_P_E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                N_P_EMouseClicked(evt);
            }
        });
        getContentPane().add(N_P_E, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 0, 170, 40));

        Tasas_e.setText("Tasas Equivalente");
        Tasas_e.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tasas_eMouseClicked(evt);
            }
        });
        getContentPane().add(Tasas_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 0, -1, 40));

        Periodica.setText("Periodica");
        Periodica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PeriodicaMouseClicked(evt);
            }
        });
        getContentPane().add(Periodica, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 80, 40));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/casa.jpg"))); // NOI18N
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 8, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/linea-gris-0_opt.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, 630, 30));

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 40));

        jButton1.setText("Encontrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encontrarBase(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        jButton2.setText("Convertir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hallarPeriodica(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Tasa periodica conocida");

        jLabel1.setText("Porcentaje");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Forma de pago");

        buttonGroup1.add(rbtnAnticipado);
        rbtnAnticipado.setText("Anticipada");

        buttonGroup1.add(rbtnVencido);
        rbtnVencido.setText("Vencida");

        jLabel3.setText("Periodo de pago");

        cboxPeriodos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Mes", "Bimestre", "Trimestre", "Semestre", "Año" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(rbtnAnticipado)
                    .addComponent(rbtnVencido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxPeriodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbtnAnticipado)
                    .addComponent(txtPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnVencido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboxPeriodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEfectivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEfectivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 220, 220));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tasa periodica a encontrar");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Forma de pago");

        buttonGroup2.add(rbtnAnticipado2);
        rbtnAnticipado2.setText("Anticipada");

        buttonGroup2.add(rbtnVencido2);
        rbtnVencido2.setText("Vencida");

        jLabel6.setText("Periodo de pago");

        cboxPeriodos2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Mes", "Bimestre", "Trimestre", "Semestre", "Año" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(rbtnAnticipado2)
                            .addComponent(rbtnVencido2))
                        .addGap(104, 104, 104))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboxPeriodos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnAnticipado2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnVencido2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboxPeriodos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel8.setText("Porcentaje");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 220, 220));

        jButton3.setText("Borrar campos");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/fondo1.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        Diseño ds = new Diseño();
        ds.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void N_P_EMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_P_EMouseClicked
        Npe n = new Npe();     
        n.setVisible(true);       
        this.dispose();
    }//GEN-LAST:event_N_P_EMouseClicked

    private void Tasas_eMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tasas_eMouseClicked
        TasasE te = new TasasE();        
        te.setVisible(true);       
        this.dispose();
    }//GEN-LAST:event_Tasas_eMouseClicked

    private void PeriodicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PeriodicaMouseClicked
        Periodica p = new Periodica();
        p.setVisible(true);        
        this.dispose();
    }//GEN-LAST:event_PeriodicaMouseClicked

    private void encontrarBase(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encontrarBase
        Interes_periodico intPe=new Interes_periodico();
        double base=Double.parseDouble(this.txtEfectivo.getText());
        String periodos=this.cboxPeriodos.getSelectedItem().toString();
        double solucion;
        
        
        if (this.rbtnAnticipado.isSelected()){
        
            switch(periodos){
                case "Dia":
                    solucion = intPe.pedidoDatosAnticipado(360, base);
                    this.txtPrueba.setText(Double.toString(solucion));
                    break;
                case "Mes":
                    solucion=intPe.pedidoDatosAnticipado(12, base);
                    this.txtPrueba.setText(Double.toString(solucion));
                    break;
                case "Bimestre":
                    solucion=intPe.pedidoDatosAnticipado(6, base);
                    this.txtPrueba.setText(Double.toString(solucion));
                    break;
                case "Trimestre":
                    solucion=intPe.pedidoDatosAnticipado(4, base);
                    this.txtPrueba.setText(Double.toString(solucion));
                    break;
                case "Semestre":
                    solucion=intPe.pedidoDatosAnticipado(2, base);
                    this.txtPrueba.setText(Double.toString(solucion));
                    break;
                case "Año":
                    solucion=intPe.pedidoDatosAnticipado(1, base);
                    this.txtPrueba.setText(Double.toString(solucion));
                    break;
            }
            
        }else if(this.rbtnVencido.isSelected()){
        
            switch(periodos){
                case "Dia":
                    solucion=intPe.pedidoDatosVencido(360, base);
                    this.txtPrueba.setText(Double.toString(solucion));
                    break;
                case "Mes":
                    solucion=intPe.pedidoDatosVencido(12, base);
                    this.txtPrueba.setText(Double.toString(solucion));
                    break;
                case "Bimestre":
                    solucion=intPe.pedidoDatosVencido(6, base);
                    this.txtPrueba.setText(Double.toString(solucion));
                    break;
                case "Trimestre":
                    solucion=intPe.pedidoDatosVencido(4, base);
                    this.txtPrueba.setText(Double.toString(solucion));
                    break;
                case "Semestre":
                    solucion=intPe.pedidoDatosVencido(2, base);
                    this.txtPrueba.setText(Double.toString(solucion));
                    break;
                case "Año":
                    solucion=intPe.pedidoDatosVencido(1, base);
                    this.txtPrueba.setText(Double.toString(solucion));
                    break;
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna opcion");
        }
    }//GEN-LAST:event_encontrarBase

    private void hallarPeriodica(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hallarPeriodica
        Interes_periodico intPe=new Interes_periodico();
        double base=Double.parseDouble(this.txtPrueba.getText());
        String periodos=this.cboxPeriodos2.getSelectedItem().toString();
        //this.txtSalida.setText(Double.toString(solucion));
        double solucion;
        
        if (this.rbtnAnticipado2.isSelected()){
        
            switch(periodos){
                case "Dia":
                    solucion=intPe.hallarPeriodicoAnticipado(360);
                    this.txtSalida.setText(Double.toString(solucion));
                    //JOptionPane.showMessageDialog(null, solucion);
                    break;
                case "Mes":
                    solucion=intPe.hallarPeriodicoAnticipado(12);
                    this.txtSalida.setText(Double.toString(solucion));
                    //JOptionPane.showMessageDialog(null, solucion);
                    break;
                case "Bimestre":
                    solucion=intPe.hallarPeriodicoAnticipado(6);
                    this.txtSalida.setText(Double.toString(solucion));
                    //JOptionPane.showMessageDialog(null, solucion);
                    break;
                case "Trimestre":
                    solucion=intPe.hallarPeriodicoAnticipado(4);
                    this.txtSalida.setText(Double.toString(solucion));
                    //JOptionPane.showMessageDialog(null, solucion);
                    break;
                case "Semestre":
                    solucion=intPe.hallarPeriodicoAnticipado(2);
                    this.txtSalida.setText(Double.toString(solucion));
                    //JOptionPane.showMessageDialog(null, solucion);
                    break;
                case "Año":
                    solucion=intPe.hallarPeriodicoAnticipado(1);
                    this.txtSalida.setText(Double.toString(solucion));
                    //JOptionPane.showMessageDialog(null, solucion);
                    break;
            }
            
        }else if(this.rbtnVencido2.isSelected()){
        
            switch(periodos){
                case "Dia":
                    solucion=intPe.hallarPeriodicoVencido(360);
                    this.txtSalida.setText(Double.toString(solucion));
                   // JOptionPane.showMessageDialog(null, solucion);
                    break;
                case "Mes":
                    solucion=intPe.hallarPeriodicoVencido(12);
                    this.txtSalida.setText(Double.toString(solucion));
                    //JOptionPane.showMessageDialog(null, solucion);
                    break;
                case "Bimestre":
                    solucion=intPe.hallarPeriodicoVencido(6);
                    this.txtSalida.setText(Double.toString(solucion));
                    //JOptionPane.showMessageDialog(null, solucion);
                    break;
                case "Trimestre":
                    solucion=intPe.hallarPeriodicoVencido(4);
                    this.txtSalida.setText(Double.toString(solucion));
                    //JOptionPane.showMessageDialog(null, solucion);
                    break;
                case "Semestre":
                    solucion=intPe.hallarPeriodicoVencido(2);
                    this.txtSalida.setText(Double.toString(solucion));
                    //JOptionPane.showMessageDialog(null, solucion);
                    break;
                case "Año":
                    solucion=intPe.hallarPeriodicoVencido(1);
                    this.txtSalida.setText(Double.toString(solucion));
                    //JOptionPane.showMessageDialog(null, solucion);
                    break;
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna opcion");
        }
    }//GEN-LAST:event_hallarPeriodica

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Periodica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Periodica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Periodica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Periodica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Periodica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Home;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel N_P_E;
    private javax.swing.JLabel Periodica;
    private javax.swing.JLabel Tasas_e;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cboxPeriodos;
    private javax.swing.JComboBox<String> cboxPeriodos2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton rbtnAnticipado;
    private javax.swing.JRadioButton rbtnAnticipado2;
    private javax.swing.JRadioButton rbtnVencido;
    private javax.swing.JRadioButton rbtnVencido2;
    public static javax.swing.JTextField txtEfectivo;
    public static javax.swing.JTextField txtPrueba;
    private javax.swing.JTextField txtSalida;
    // End of variables declaration//GEN-END:variables
}
