/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diseño_primero;

import Modelo.primero.TasasE_modelo;
import diseño_primero.Diseño;
import diseño_primero.Npe;
import diseño_primero.Periodica;
import java.awt.Button;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian Herrera
 */
public class TasasE extends javax.swing.JFrame {

    int seleccion = 0;

    public TasasE() {
        initComponents();
        setLocationRelativeTo(null);
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupNominal = new javax.swing.ButtonGroup();
        btnGroupPeriodica = new javax.swing.ButtonGroup();
        N_P_E = new javax.swing.JLabel();
        Tasas_e = new javax.swing.JLabel();
        Periodica = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        Home = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnNominalA = new javax.swing.JButton();
        btnPeriodica = new javax.swing.JButton();
        btnEfectiva = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        txtPorcentajeP = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        radAnticipadaP = new javax.swing.JRadioButton();
        radVencidaP = new javax.swing.JRadioButton();
        jLabel59 = new javax.swing.JLabel();
        cmbPeriodica = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        txtPorcentajeN = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        radAnticipadaN = new javax.swing.JRadioButton();
        radVencidaN = new javax.swing.JRadioButton();
        jLabel55 = new javax.swing.JLabel();
        cmbNominal = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        txtPorcentajeE = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ADV = new javax.swing.JTextField();
        AMV = new javax.swing.JTextField();
        ABV = new javax.swing.JTextField();
        ATV = new javax.swing.JTextField();
        ASV = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ADA = new javax.swing.JTextField();
        AMA = new javax.swing.JTextField();
        ABA = new javax.swing.JTextField();
        ATA = new javax.swing.JTextField();
        ASA = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        AAV = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        AAA = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DV = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        DA = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        MV = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        MA = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        BV = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        BA = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        TV = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        TA = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        SV = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        SA = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        EA = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        AA = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        N_P_E.setText("Nominal / Periodica / Efectiva");
        N_P_E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                N_P_EMouseClicked(evt);
            }
        });
        getContentPane().add(N_P_E, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 40));

        Tasas_e.setText("Tasas Equivalente");
        Tasas_e.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tasas_eMouseClicked(evt);
            }
        });
        getContentPane().add(Tasas_e, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 6, -1, 30));

        Periodica.setText("Periodica");
        Periodica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PeriodicaMouseClicked(evt);
            }
        });
        getContentPane().add(Periodica, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 6, 70, 30));

        Menu.setBackground(new java.awt.Color(255, 255, 255));
        Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/casa.jpg"))); // NOI18N
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addContainerGap(767, Short.MAX_VALUE)
                .addComponent(Home)
                .addContainerGap())
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Home)
                .addGap(26, 26, 26))
        );

        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        jButton1.setText("Convertir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, -1, -1));

        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, -1, -1));

        btnNominalA.setText("Nominal Anual");
        btnNominalA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNominalAActionPerformed(evt);
            }
        });
        getContentPane().add(btnNominalA, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        btnPeriodica.setText("Periodica");
        btnPeriodica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeriodicaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPeriodica, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        btnEfectiva.setText("Efectiva Anual");
        btnEfectiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfectivaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEfectiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(230, 150));

        jLabel56.setText("Porcentaje");

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("Forma de pago");

        btnGroupPeriodica.add(radAnticipadaP);
        radAnticipadaP.setText("Anticipada");

        btnGroupPeriodica.add(radVencidaP);
        radVencidaP.setText("Vencida");

        jLabel59.setText("Periodo de pago Menor");

        cmbPeriodica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Mes", "Bimestre", "Trimestre", "Semestre", "Año" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel59, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radAnticipadaP, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radVencidaP, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbPeriodica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel58)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radAnticipadaP, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radVencidaP, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel59)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbPeriodica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel56)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPorcentajeP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel56)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPorcentajeP)
                    .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(230, 150));

        jLabel52.setText("Porcentaje");

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("Forma de pago");

        btnGroupNominal.add(radAnticipadaN);
        radAnticipadaN.setText("Anticipada");

        btnGroupNominal.add(radVencidaN);
        radVencidaN.setText("Vencida");

        jLabel55.setText("Periodo de pago Menor");

        cmbNominal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Mes", "Bimestre", "Trimestre", "Semestre", "Año" }));
        cmbNominal.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel55, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radAnticipadaN, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radVencidaN, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbNominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radAnticipadaN, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radVencidaN, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel55)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbNominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtPorcentajeN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPorcentajeN)
                    .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel60.setText("Porcentaje");

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel63.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("Periodos");

        jLabel68.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("1");

        jLabel62.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("Por ");

        jLabel69.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel69.setText("Año");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel63, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel62, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel69, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel68, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel63)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel62)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel69)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel68)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel60)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtPorcentajeE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel60)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPorcentajeE)
                    .addComponent(jLabel61, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 220, 150));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nominales");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 1, 290, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Vencidas");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 23, 155, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Anticipadas");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 23, 141, -1));

        ADV.setEditable(false);
        jPanel4.add(ADV, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 45, 70, -1));

        AMV.setEditable(false);
        jPanel4.add(AMV, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 75, 70, -1));

        ABV.setEditable(false);
        jPanel4.add(ABV, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 105, 70, -1));

        ATV.setEditable(false);
        jPanel4.add(ATV, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 135, 70, -1));

        ASV.setEditable(false);
        jPanel4.add(ASV, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 165, 70, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 45, 21, 24));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 75, 21, 24));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 105, 21, 24));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 165, 21, 24));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 135, 21, 24));

        jLabel13.setText("A.B.V");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 113, 35, -1));

        jLabel14.setText("A.D.V");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 53, 35, -1));

        jLabel15.setText("A.T.V");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 143, 35, -1));

        jLabel17.setText("A.M.V");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 83, 35, -1));

        jLabel16.setText("A.S.V");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 173, 35, -1));

        ADA.setEditable(false);
        jPanel4.add(ADA, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 45, 70, -1));

        AMA.setEditable(false);
        jPanel4.add(AMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 75, 70, -1));

        ABA.setEditable(false);
        jPanel4.add(ABA, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 105, 70, -1));

        ATA.setEditable(false);
        jPanel4.add(ATA, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 135, 70, -1));

        ASA.setEditable(false);
        jPanel4.add(ASA, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 165, 70, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 45, 21, 24));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 75, 21, 24));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 105, 21, 24));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 165, 21, 24));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 135, 21, 24));

        jLabel23.setText("A.B.A");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 113, 35, -1));
        jLabel23.getAccessibleContext().setAccessibleName("40");

        jLabel24.setText("A.D.A");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 53, 35, -1));
        jLabel24.getAccessibleContext().setAccessibleName("40");

        jLabel25.setText("A.T.A");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 143, 35, -1));
        jLabel25.getAccessibleContext().setAccessibleName("40");

        jLabel26.setText("A.M.A");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 83, 35, -1));
        jLabel26.getAccessibleContext().setAccessibleName("40");

        jLabel27.setText("A.S.A");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 173, 35, -1));
        jLabel27.getAccessibleContext().setAccessibleName("40");

        AAV.setEditable(false);
        jPanel4.add(AAV, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 195, 70, -1));

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N
        jPanel4.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 195, 21, 24));

        jLabel65.setText("A.A.V");
        jPanel4.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 199, 35, -1));

        AAA.setEditable(false);
        jPanel4.add(AAA, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 195, 70, -1));

        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N
        jPanel4.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 195, 21, 24));

        jLabel67.setText("A.A.A");
        jPanel4.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 203, 35, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 325, 230));
        jPanel4.getAccessibleContext().setAccessibleName("40");

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Periodicas");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 300, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Vencidas");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 23, 155, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Anticipadas");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 23, 133, -1));

        DV.setEditable(false);
        jPanel6.add(DV, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 45, 70, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 45, 21, 24));

        jLabel29.setText("D.V");
        jPanel6.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 53, 35, -1));

        DA.setEditable(false);
        jPanel6.add(DA, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 45, 70, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 45, 21, 24));

        jLabel31.setText("D.A");
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 53, 35, -1));

        MV.setEditable(false);
        jPanel6.add(MV, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 75, 70, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 75, 21, 24));

        jLabel33.setText("M.V");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 83, 35, -1));

        MA.setEditable(false);
        jPanel6.add(MA, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 75, 70, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 75, 21, 24));

        jLabel35.setText("M.A");
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 83, 35, -1));

        BV.setEditable(false);
        jPanel6.add(BV, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 105, 70, -1));

        jLabel36.setText("B.V");
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 113, 35, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N
        jPanel6.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 105, 21, 24));

        BA.setEditable(false);
        jPanel6.add(BA, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 105, 70, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N
        jPanel6.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 105, 21, 24));

        jLabel39.setText("B.A");
        jPanel6.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 113, 35, -1));

        TV.setEditable(false);
        jPanel6.add(TV, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 135, 70, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N
        jPanel6.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 135, 21, 24));

        jLabel41.setText("T.V");
        jPanel6.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 143, 35, -1));

        TA.setEditable(false);
        jPanel6.add(TA, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 135, 70, -1));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N
        jPanel6.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 135, 21, 24));

        jLabel43.setText("T.A");
        jPanel6.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 143, 35, -1));

        SV.setEditable(false);
        jPanel6.add(SV, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 165, 70, -1));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N
        jPanel6.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 165, 21, 24));

        jLabel45.setText("S.V");
        jPanel6.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 173, 35, -1));

        SA.setEditable(false);
        jPanel6.add(SA, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 165, 70, -1));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N
        jPanel6.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 165, 21, 24));

        jLabel47.setText("S.A");
        jPanel6.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 173, 35, -1));

        EA.setEditable(false);
        jPanel6.add(EA, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 195, 70, -1));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N
        jPanel6.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 195, 21, 24));

        jLabel49.setText("E.A");
        jPanel6.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 203, 35, -1));

        AA.setEditable(false);
        jPanel6.add(AA, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 195, 70, -1));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/por-ciento.jpg"))); // NOI18N
        jPanel6.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 195, 21, 24));

        jLabel51.setText("A.A");
        jPanel6.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 203, 35, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 300, 230));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/linea-gris-0_opt.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 26, 780, 20));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diseño/imagenes/fondo2-lanczos3.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 552));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        Diseño ds = new Diseño();
        ds.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);

        btnNominalA.setVisible(true);
        btnPeriodica.setVisible(true);
        btnEfectiva.setVisible(true);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void N_P_EMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_P_EMouseClicked
        Npe n = new Npe();

        n.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_N_P_EMouseClicked

    private void Tasas_eMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tasas_eMouseClicked
        TasasE te = new TasasE();

        te.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_Tasas_eMouseClicked

    private void PeriodicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PeriodicaMouseClicked
        Periodica p = new Periodica();

        p.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_PeriodicaMouseClicked

    private void btnNominalAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNominalAActionPerformed
        jPanel2.setVisible(true);
        btnPeriodica.setVisible(false);
        btnEfectiva.setVisible(false);

        seleccion = 1;

//        TasasE_modelo ts = new TasasE_modelo();
//        ts.NominalAnticipada();
    }//GEN-LAST:event_btnNominalAActionPerformed

    private void btnPeriodicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeriodicaActionPerformed
        jPanel1.setVisible(true);
        btnNominalA.setVisible(false);
        btnEfectiva.setVisible(false);

        seleccion = 2;
    }//GEN-LAST:event_btnPeriodicaActionPerformed

    private void btnEfectivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfectivaActionPerformed
        jPanel3.setVisible(true);
        btnNominalA.setVisible(false);
        btnPeriodica.setVisible(false);

        seleccion = 3;
    }//GEN-LAST:event_btnEfectivaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TasasE_modelo ts = new TasasE_modelo();

        switch (seleccion) {
            case 1:
                if (radAnticipadaN.isSelected() == true) {
                    ts.NominalAnticipada();
                } else if (radVencidaN.isSelected() == true) {
                    ts.NominalVencida();
                }
                break;

            case 2:
                if (radAnticipadaP.isSelected() == true) {
                    ts.PeriodicaAnticipada();
                } else if (radVencidaP.isSelected() == true) {
                    ts.PeriodicaVencida();
                }
                break;

            case 3:
                if (btnEfectiva.isEnabled()) {
                    ts.Efectiva();
                }
                break;

            default:
                break;
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TasasE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TasasE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TasasE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TasasE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TasasE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField AA;
    public static javax.swing.JTextField AAA;
    public static javax.swing.JTextField AAV;
    public static javax.swing.JTextField ABA;
    public static javax.swing.JTextField ABV;
    public static javax.swing.JTextField ADA;
    public static javax.swing.JTextField ADV;
    public static javax.swing.JTextField AMA;
    public static javax.swing.JTextField AMV;
    public static javax.swing.JTextField ASA;
    public static javax.swing.JTextField ASV;
    public static javax.swing.JTextField ATA;
    public static javax.swing.JTextField ATV;
    public static javax.swing.JTextField BA;
    public static javax.swing.JTextField BV;
    public static javax.swing.JTextField DA;
    public static javax.swing.JTextField DV;
    public static javax.swing.JTextField EA;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Home;
    public static javax.swing.JTextField MA;
    public static javax.swing.JTextField MV;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel N_P_E;
    private javax.swing.JLabel Periodica;
    public static javax.swing.JTextField SA;
    public static javax.swing.JTextField SV;
    public static javax.swing.JTextField TA;
    public static javax.swing.JTextField TV;
    private javax.swing.JLabel Tasas_e;
    private javax.swing.JButton btnEfectiva;
    public static javax.swing.ButtonGroup btnGroupNominal;
    private javax.swing.ButtonGroup btnGroupPeriodica;
    public static javax.swing.JButton btnNominalA;
    private javax.swing.JButton btnPeriodica;
    public static javax.swing.JComboBox<String> cmbNominal;
    public static javax.swing.JComboBox<String> cmbPeriodica;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    public static javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    public static javax.swing.JRadioButton radAnticipadaN;
    private javax.swing.JRadioButton radAnticipadaP;
    public static javax.swing.JRadioButton radVencidaN;
    private javax.swing.JRadioButton radVencidaP;
    public static javax.swing.JTextField txtPorcentajeE;
    public static javax.swing.JTextField txtPorcentajeN;
    public static javax.swing.JTextField txtPorcentajeP;
    // End of variables declaration//GEN-END:variables
}
